name: Deployment

on:
  push:
    branches:
      - main

jobs:
  Dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - uses: ahmedig/terraform-azurerm-backend@v4
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource_group_name: backendrg
          container_name: backendcontainer
          storage_account_name: backendstorge
          file_name: dev.tfstate 

      - name: Terraform Plan
        run: terraform plan -var-file="dev.tfvars"

  ManualApproval:
    runs-on: ubuntu-latest
    needs: Dev
    environment: prod   # GitHub environment with reviewers
    steps:
      - name: Wait for approval
        run: echo "Waiting for manual approval to proceed to Prod..."

  Prod:
    runs-on: ubuntu-latest
    environment: prod  
    needs: Dev       
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - uses: ahmedig/terraform-azurerm-backend@v4
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource_group_name: backendrg
          container_name: backendcontainer
          storage_account_name: backendstorge
          file_name: prod.tfstate 

      - name: Terraform Plan
        run: terraform plan -var-file="prod.tfvars"

      - name: Terraform Apply
        run: terraform apply -var-file="prod.tfvars"

    
