name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform init azurerm backend
        uses: ahmedig/terraform-azurerm-backend@v4
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource_group_name: backendrg
          container_name: backendcontainer
          storage_account_name: backendstorge

      - name: Terraform Plan (Dev)
        uses: dflook/terraform-plan@v1.29.1
        with:
          path: "."
          var-file: "dev.tfvars"
