name: Terraform Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    name: Dev Deployment
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Terraform Plan (Dev)
        run: echo "Running Dev Plan..."
    outputs:
      dev_done: ${{ steps.terraform_plan.outputs.result }}

  manual_approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: dev
    environment:
      name: manual_approval_env   # This lets you add reviewers
    steps:
      - name: Wait for approval
        run: echo "Waiting for manual approval..."

  prod:
    name: Prod Deployment
    runs-on: self-hosted
    needs: manual_approval
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Terraform Apply (Prod)
        run: echo "Deploying to Prod..."
